name: New UPDATER release

on:
  release:
    types: [published]

jobs:
  build-and-push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: m4rc02u1f4a4/gantu-updater:latest
          file: updater/Dockerfile
          context: updater

      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: m4rc02u1f4a4/gantu-updater:${{  github.ref_name }}
          file: updater/Dockerfile
          context: updater